language: node_js
git:
  depth: 1
node_js: lts/*
install:
  - npm i -g truffle
  - npm i -g ganache-cli
before_script:
  - ganache-cli --accounts 500 >ganache.log 2>&1 &
  - sleep 5
script:
  - npm run test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
notifications:
  email:
    - dev-notifications@noblockno.party
