language: node_js
node_js: lts/*
cache: yarn
install:
  - npm i -g truffle
  - npm i -g ganache-cli
before_script:
  - ganache-cli --accounts 500
  - sleep 5
script:
  - yarn test
after_script:
  - yarn coverage && cat coverage/lcov.info | coveralls
notifications:
  email:
    - dev-notifications@noblockno.party
